### ISSUE TITLE
pika相关

### ISSUE THREAD

**Issue by utf-gbk** [aox-lei/scrapy-rabbitmq-scheduler#1]
1.connection.py文件中队列优先级是否可改成参数化配置；

2.pipline中的队列发布时会出现channel关闭的问题；

**Comment by aox-lei** [comment]
@utf-gbk 
1. 可以, 稍后我改下
2. 能否给具体的场景错误等?

**Comment by Wowgreat** [comment]
持续运行会有这个错误
`2020-06-08 10:43:27 [pika.adapters.utils.io_services_utils] ERROR: _AsyncBaseTransport._produce() failed, aborting connection: error=ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None); sock=<socket.socket fd=792, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.195', 50998), raddr=('192.168.1.198', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\pika\adapters\utils\io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\pika\adapters\utils\io_services_utils.py", line 820, in _produce
    self._tx_buffers[0])
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\pika\adapters\utils\io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\pika\adapters\utils\io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Traceback (most recent call last):
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\pika\adapters\utils\io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\pika\adapters\utils\io_services_utils.py", line 820, in _produce
    self._tx_buffers[0])
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\pika\adapters\utils\io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\pika\adapters\utils\io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2020-06-08 10:43:27 [pika.adapters.base_connection] ERROR: connection_lost: StreamLostError: ("Stream connection lost: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)",)
2020-06-08 10:43:27 [pika.adapters.blocking_connection] ERROR: Unexpected connection close detected: StreamLostError: ("Stream connection lost: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)",)
Unhandled Error
Traceback (most recent call last):
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\commands\crawl.py", line 58, in run
    self.crawler_process.start()
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\crawler.py", line 293, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\twisted\internet\base.py", line 1283, in run
    self.mainLoop()
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\twisted\internet\base.py", line 1292, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\twisted\internet\base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\utils\reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\core\engine.py", line 122, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\core\engine.py", line 149, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy_rabbitmq_scheduler\scheduler.py", line 130, in next_request
    mframe, hframe, body = self.queue.pop(no_ack=no_ack)
builtins.TypeError: 'NoneType' object is not iterable

2020-06-08 10:43:27 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\commands\crawl.py", line 58, in run
    self.crawler_process.start()
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\crawler.py", line 293, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\twisted\internet\base.py", line 1283, in run
    self.mainLoop()
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\twisted\internet\base.py", line 1292, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\twisted\internet\base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\utils\reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\core\engine.py", line 122, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy\core\engine.py", line 149, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "D:\Users\neo\Miniconda3\envs\py36\lib\site-packages\scrapy_rabbitmq_scheduler\scheduler.py", line 130, in next_request
    mframe, hframe, body = self.queue.pop(no_ack=no_ack)
builtins.TypeError: 'NoneType' object is not iterable
`

**Comment by aox-lei** [comment]
抱歉，一直没来得及处理，已解决
