### ISSUE TITLE
Channel is closed

### ISSUE THREAD

**Issue by WangDePeng7** [aox-lei/scrapy-rabbitmq-scheduler#4]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\scrapy_rabbitmq_scheduler\pipelines.py", line 31, in process_item
    self.channel.basic_publish(exchange='',
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pika\adapters\blocking_connection.py", line 2205, in basic_publish
    self._impl.basic_publish(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pika\channel.py", line 421, in basic_publish
    self._raise_if_not_open()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pika\channel.py", line 1389, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.

我在获取 RabbitMQ 的数据之后，进行抓取网页数据，然后向另一个Queue推送消息，刚开始是没有问题的，
程序一直处于运行状态，间隔20分钟~30分钟之后，再向Queue推送消息的时候，会出现 Channel is closed 的问题，还有下一个问题：

 [pika.adapters.utils.io_services_utils] INFO: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None); <socket.socket fd=492, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.8.200', 50751), raddr=('10.0.253.201', 5672)>

**Comment by WangDePeng7** [comment]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\scrapy_rabbitmq_scheduler\pipelines.py", line 31, in process_item
    self.channel.basic_publish(exchange='',
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pika\adapters\blocking_connection.py", line 2212, in basic_publish
    self._flush_output(self._message_confirmation_result.is_ready)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pika\adapters\blocking_connection.py", line 1336, in _flush_output
    self._connection._flush_output(lambda: self.is_closed, *waiters)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pika\adapters\blocking_connection.py", line 522, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.StreamLostError: Stream connection lost: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)

**Comment by utf-gbk** [comment]
同，我也遇到了相同的问题，channel 关闭之后 没有重新创建

 File "/home/etrump/.pyenv/versions/hunt/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/etrump/.pyenv/versions/hunt/lib/python3.7/site-packages/scrapy_rabbitmq_scheduler/pipelines.py", line 33, in process_item
    body=data)
  File "/home/etrump/.pyenv/versions/hunt/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2210, in basic_publish
    mandatory=mandatory)
  File "/home/etrump/.pyenv/versions/hunt/lib/python3.7/site-packages/pika/channel.py", line 421, in basic_publish
    self._raise_if_not_open()
  File "/home/etrump/.pyenv/versions/hunt/lib/python3.7/site-packages/pika/channel.py", line 1389, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.

**Comment by Wowgreat** [comment]
+1

**Comment by Wowgreat** [comment]
![image](https://user-images.githubusercontent.com/25166255/83989398-dac90c00-a978-11ea-8866-3261c7ac4cf5.png)
我在 schduler中修改了这些代码，目前可以持续稳定运行了

**Comment by Wowgreat** [comment]
if  not self.queue:
    self._make_queue(self.spider.queue_name)

**Comment by aox-lei** [comment]
已经优化
